destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/spl-pdf"
port: 4011
output: pdf
product: spl
print_title: SPL Global Telemetry
print_subtitle: version 2.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: spl_sidebar
