# Site settings
title: SPL Satellite Telemetry
email: pb@envirover.com
description: >
  SPL Satellite Telemetry.

baseurl: "/spldocs" # the subpath of your site, e.g. /blog/
url: https://envirover.com/spldocs # the base hostname & protocol for your site
git_address: https://github.com/envirover/spldocs
git_edit_address: https://github.com/envirover/spldocs

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
